# Generated by Django 4.1.2 on 2022-10-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('hash', models.CharField(max_length=128)),
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('last_name', models.CharField(max_length=30)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=40)),
            ],
        ),
    ]
